'use client';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowDown,Menu,X,ShieldCheck,MapPin,Clock3,MessageCircle,House,Building2,Store,Factory} from 'lucide-react';
export const whatsapp='https://wa.me/541173649101?text='+encodeURIComponent('Hola, vi la página de Almagro Fumigación y quisiera consultar por un servicio.');
export function WhatsAppIcon(){return <svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.7 7.5L3 20.5l1.4-4.7a8.5 8.5 0 1 1 16.1-4.2Z"/><path d="M8 7.5c-.8.7-.3 3.2 1.9 5.4s4.7 2.7 5.4 1.9l.8-1.2-2.5-1.3-.9.8a7 7 0 0 1-2.7-2.7l.8-.9L9.5 7Z"/></svg>}
export function CTA({children='Solicitar por WhatsApp',yellow=false}:{children?:React.ReactNode;yellow?:boolean}){return <a className={'button '+(yellow?'yellow':'green')} href={whatsapp} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>{children}<ArrowUpRight size={18}/></a>}
const links=[['Inicio','inicio'],['Servicios','servicios'],['¿Por qué elegirnos?','nosotros'],['Opiniones','opiniones'],['Cobertura','cobertura'],['Preguntas frecuentes','preguntas']];
export function Header(){const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(window.scrollY>30);f();window.addEventListener('scroll',f,{passive:true});return()=>window.removeEventListener('scroll',f)},[]);return <header className={'nav '+(scrolled?'scrolled':'')}><div className="nav-inner"><a href="#inicio" className="brand" aria-label="Almagro Fumigación, inicio"><img src="/logo.webp" alt="Logo original de Almagro Fumigación" width="54" height="54"/><span>ALMAGRO<small>FUMIGACIÓN</small></span></a><nav className={'nav-links '+(open?'open':'')} aria-label="Navegación principal">{links.map(([label,id])=><a href={'#'+id} key={id} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="nav-cta" href={whatsapp} target="_blank" rel="noopener noreferrer">Solicitar <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={open?'Cerrar menú':'Abrir menú'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
export function Hero(){const sectors=[{Icon:House,label:'Hogares'},{Icon:Building2,label:'Empresas'},{Icon:Store,label:'Comercios'},{Icon:Factory,label:'Industrias'}];return <><section className="hero" id="inicio"><img className="hero-image" src="/fumigacion.webp" alt="Profesional con traje de protección realizando un tratamiento en el jardín de una vivienda" width="1672" height="941" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-content"><h1>PROTEGEMOS<br/><em>LO QUE IMPORTA</em></h1><p>Soluciones profesionales en control<br/>de plagas para hogares y empresas</p><div className="hero-actions"><CTA/><a className="text-button" href="#servicios">Ver servicios <ArrowDown size={17}/></a></div></div><div className="hero-sectors" aria-label="Espacios que atendemos">{sectors.map(({Icon,label})=><div className="hero-sector" key={label}><Icon size={30} strokeWidth={1.7}/><span>{label}</span></div>)}</div></section><section className="trust"><div className="container trust-grid">{[{Icon:Clock3,title:'Respuesta rápida',text:'Atención ágil por WhatsApp'},{Icon:ShieldCheck,title:'Tratamientos efectivos',text:'Soluciones para cada plaga'},{Icon:MapPin,title:'Cobertura CABA',text:'Servicio a domicilio'},{Icon:MessageCircle,title:'Seguimiento',text:'También después del tratamiento'}].map(({Icon,title,text})=><div className="trust-item" key={title}><span className="icon-box"><Icon size={23}/></span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></section></>}



